### ISSUE TITLE
Cache / Buffer settings and Cache fulled

### ISSUE THREAD

**Issue by iz8mbw** [ddurdle/Amazon-Cloud-Drive-for-KODI#12]
Hi.
First thank you for this fantastic addon.
I'm testing it on a Raspberry Pi 2 running LibreELEC.
When I try to stream a .mkv file I obtain, after a while, the "Cache fulled" message from Kodi.
I try also to reduce to 0% the cache size but I still have this warning and also the stream needs lots of seconds to go in play.
Then, why also if I reduce to 0% the cache size I obtain "Cache fulled" message from Kodi?
And why I still needs to wait lots of seconds to go in play?
I expect that if I reduce to 0% the cache size the stream should starts about immediately and, if my Internet bandwidth is not enough, possibly, the playback will stop and will starts again to buffer it using the default Kodi buffer size (or using, if exist, the file "advancedsettings.xml" where a buffer size can be configured).
May be there is a bug in the addon's Cache configurations?

In addiction, why do not chance the cache size in Megabytes instead of %?
Consider that, for example, 10% of size for a 10 GB mkv is not the same of 10% of size for a 700MB avi file...
I suggest to change it in MB, and for me, I will choose to set it to 10 MB.

Thanks

**Comment by ddurdle** [comment]
You are playing "Play + Cache" or have "always cache playback" enabled in the add-on settings when you are playing back?

I will implement the MB selection.

**Comment by iz8mbw** [comment]
I have the "always cache playback" disabled.
Where is "Play + Cache"?

**Comment by ddurdle** [comment]
Right click on the media file and select Play + Cache.

**Comment by iz8mbw** [comment]
If I use "Play + Cache" the video does not starts

**Comment by ddurdle** [comment]
will investigate.

**Comment by ddurdle** [comment]
Do you have a cache folder set?  It worked when I tested.

![image](https://cloud.githubusercontent.com/assets/851508/18225023/3068e1f6-71b7-11e6-94b5-5e3ee87df454.png)

**Comment by iz8mbw** [comment]
Yes, folder already setted.
I tested on a small .mp4, it seem that the connecion (TCP connection) starts but no video is seen...

`tcp        0      0 192.168.1.21:39276      ec2-54-76-79-202.eu-west-1.compute.amazonaws.com:https ESTABLISHED`

**Comment by iz8mbw** [comment]
Then , if I wait some minutes, and then I'll try again the video will starts.

**Comment by ddurdle** [comment]
do you get a cache dialog popup?

**Comment by ddurdle** [comment]
What % do you have set?

**Comment by iz8mbw** [comment]
About cache dialog popup: The first time yes (when video does not starts) the second time no (when video starts)

**Comment by iz8mbw** [comment]
Now it's 0%

**Comment by iz8mbw** [comment]
it seem that when the "cache dialog popup" will NOT appears the video is seen

**Comment by iz8mbw** [comment]
And, with a .mkv of 12 GB nothing happens, with a .mkv of 5 GB I was able to see vdeo (always when the cache dialog popup will not appears

**Comment by ddurdle** [comment]
You cannot have it at 0% or it won't playback correct.  Try with higher value.

It plays back when you try a second time because it is caching in background and it is > 0% by the time you playback the second time.  Caching dialog only shows when you first play+cache.

**Comment by iz8mbw** [comment]
I have tried to incrase the % and yes, it works but it seem that after having clicked for the first time "Play + Cache" now all videos strart immeditely and the buffed go on during playing.
Now I dont' have more the Cache fulled warning.
I don't know why there is this strange behavior, but I like now how it works: I select the video and it starts immediately and the buffer goes on.
Is it the deafult behavior that untill now I did not see for some reasons?
The only issue that I still have is that a .mkv file of about 12GB does not starts. So it seem that for "large" file the stream does not start.

**Comment by iz8mbw** [comment]
Hi again.
OK, now I uderstood and I would have some suggestions and observations about how the addon works.

**About "Play + Cache" feature:**


It seem that when we talk about "cache" your addon wants to cache on File System and when I was not able to "Play + Cache" the 12GB .mkv file the problem is that I do not have 12GB of free space on my Raspberry Pi..... :-)
This the reason I was not able to play the 12GB .mkv.

So, how the addon works for the feature "Play + Cache", for me is unusable beacuse I don't have enough free disk space.

In general, about the "idea" of cache I don't like to cache on File System. In general the concept of "cache" or, better to say "buffer", is in RAM. And a "buffer" will never contains a big quantity of MB. So the "%" of buffer size could create problems for very large files.
I use also other stream addon that scrapes the video file from HTML, but all of them use buffer in RAM, not on file system and they works very well.

I suggest to you to completely remove the cache in "%" and switch to Mega Bytes only (with a maxium size limit, example 100 MB).


**About "default" play method:**

Well, this is my preferite and more fast play method. It seem that will never buffer on File System (also because I have resetted the addon and never again enable the path for store the cache file on File System).

But I cannot understand how many MegaBytes (or how many "%") it will go to use for this cache that it seem to do in RAM.
If I play a not big size file, it seem all OK, BUT when I want to play a 12GB .mkv file I obtain, after a while anf before the viseo starts, the "Cache fulled" message from Kodi. Then, in this case, I expect that the addon is caching in RAM and it will go to full the maxium size of the cache of Kodi (for my system: Raspberry Pi 2).

So it seem, for a reason that I do not know, that for this 12GB .mkv it will use a really big quantity of cache size (so RAM size). Why buffer so much? Why or where this RAM buffer size can be choosen?

Then in conclusion, please, is it possible in a next version of this addon to choose the RAM buffer size in Mega Bytes?
In this way, I expect that after I click on the file, it will starts to buffer in RAM, for example 10MB, and the video will starts to play and then it will go on to bufffer (during play) thanks to the default Kodi buffer size (or using, if exist, the file "advancedsettings.xml" where a buffer size can be configured).
As mentioned before I use also other stream addon that scrapes the video file from HTML and all of them use the buffer in RAM and they works very well.

Many thanks!

**Comment by ddurdle** [comment]
The default behaviour is to use KODI for caching and playback.  So the buffer full error is coming from KODI.  It requires tweaking with the buffer configuration in KODI.

For very large files, I sometimes get this alert from KODI, but the playback is unaffected.  If I'm on a slow connection and get the alert, I may get some buffering and stuttering.

To learn more about configuring the cache -> http://androidpcreview.com/fix-kodi-buffering-problems-heres-how-to-modify-the-kodi-cache/2611/

The add-on caching method is for those want to pre-fetch a large part of the file (hence the %) so they can playback without buffering issues.  Also useful for those who want to replay the same file multiple times, without streaming it more then once.   It does require adequate storage.

I'll see if a check can be added for disk space.

**Comment by iz8mbw** [comment]
I already have the file "advancedsettings.xml" configured into my LibreELEC / OpenELEC and it works fine, I have 50 MB of cache (buffer), see here:

`<advancedsettings>
  <network>
    <buffermode>1</buffermode>
    <cachemembuffersize>52428800</cachemembuffersize>
  </network>
</advancedsettings>`

I think that THE addon can be upgraded by works in 2 ways:

1. Buffer in RAM a quantity (better in MB) of stream and then play (and still buffer during play thanks to file "advancedsettings.xml")
2. Starts stream immediately and buffer in RAM in the same time (thanks to file "advancedsettings.xml")

In my case and my experiece, the most addon works in point 2 way: starts stream and during play it buffering.
I have a 100 Mb/s Internet connection so in my case both are OK.

But you did not answer to my question about Kodi message of Full cache: When I start to play a stream of a 12GB mkv I obtain the Full cache meesage, **what is the size of the cache in RAM of your addon? Can be this quantity of RAM cache modified / configurable?**

If I play the exactly same 12 GB mkv file stored in a hard disk of my PC via Windows share (Samba / CIFS) I do not have this error and the cache size is always given from "advancedsettings.xml".
So If I use 50 MB of RAM cache my Kodi does not give the error to me.
I'm quite sure that I have the "Cache full" message from Kodi it's beacuse the addon is using the RAM cache and it will go to full it!

Thanks.

**Comment by ddurdle** [comment]
I do not buffer in RAM in my plugin.  I hand the stream over to KODI to playback.  So it will buffer as per what it has been configured to buffer with https streams.

At the point the stream is handed over to KODI to playback, it is out of the plugin's scope.

I never get cache errors when I playback using files even if it is a file on a network device.  I don't believe the same cache buffering is in play.  KODI doesn't treat these kinds of files as network streams.

**Comment by iz8mbw** [comment]
I don't know what think and I don't know how to solve.
If my maxium buffer size, given only from the file "advancedsettings.xml", is 50 MB and your addon will not add others cache, my question is: why Kodi full the cache with your addon?
Why the same file that I stream via Samba will not full the same cache size?

I will more investigate, hope you will do the same.
Thanks!

**Comment by ddurdle** [comment]
Do you get playback working or does it stop.  Even though when I stream large files via https, if I get the error, the playback continues.  It is more of a warning that it would like to cache more then there is buffer space.

I use a large range of devices, including some Raspberry Pi A devices, and they only have 256mb RAM.  OSMC is highly optimized to use 100% of all the memory available.  This is why I don't explicitly buffer and cache in the plugin, I pass it over to KODI, because the user's device will be highly optimized based on what device it is.  I am not out of possibility of adding additional features such as this, if there is a need.  It just won't be the default.

Samba doesn't use KODI stream caching.  It loads into memory parts of the file, but it doesn't provide caching errors.  If I open a > 9GB video file on my Pi A, it causes it to reboot (runs out of memory), but there is no cache error or buffer full.

**Comment by ddurdle** [comment]
Here is a good synopsis:  http://kodi.wiki/view/Caches_explained

I stick to letting KODI manage the cache (video cache).  I provide the option to use disk cache (play + cache) as a resort for people with slow connections (mentioned in section 2 of that wiki).  Even if it fills up, playback should work.

Caching by samba or other network filesystem systems is handled outside of KODI (by the service running on the OS).

**Comment by iz8mbw** [comment]
Hi.
OK now it's more clear, thanks!
Yes the video palyback is going on also with the cache warning from Kodi.
Just for your info I had benefits adding the field "readbufferfactor" setted to "20" to the file "advancedsettings.xml" for ther Video cache.
It seem that now is more fast to download data so the buffer will reach its maxium value in less time. Often I don't have more the cache filled warning.

So now my "advancedsettings.xml" file is:
`
<advancedsettings>
  <network>
    <buffermode>1</buffermode>
    <cachemembuffersize>52428800</cachemembuffersize>
    <readbufferfactor>20</readbufferfactor>
  </network>
</advancedsettings>
`
Anyway about "Paly + cache" I hope that you will upgrade the feature by adding the "MB" option so I can test/use it using a fixed size of storage (on File System) cache  independently of the file size.
I expect that if I want to play a 12GB file and I have only 6GB of free space on the device, by using a fixed size of storage (on File System) cache in MB I can use this feature beacuse it will go to use on the file system only the size specified in Mega Bytes.
Example: file size 12GB, free space 6GB, Cache on File System 20 MB: the addon should use only 20 MB on the file system.
Again thanks!

**Comment by ddurdle** [comment]
I have some ideas around implementing caching in a completely different way.  I will update this issue when I have something to test.

**Comment by iz8mbw** [comment]
Great! Thank you.

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
