### ISSUE TITLE
Support for Cryptomator (alternative encryption to encFS)

### ISSUE THREAD

**Issue by CENGOiSM** [ddurdle/Amazon-Cloud-Drive-for-KODI#14]
HI (and thank you for this add-on first of all 👍 ),

I was looking for a secure encryption on cloud drives when I find out about encFS.
But at the same time I've read that there are methods found to possibly decrypt encFS.

Searching for an alternative I stumbled over [this encryption named Cryptomator](https://github.com/cryptomator/cryptomator). Very easy setup and looks promising too. So my question: Could this opensource encryption be implemented? Is it too much work to do? Or is encFS secure enough for media files (and in addition to that I can still use cryptomator for sensible private files).

I apologize for my bad english if there are some typos. I'm probably too paranoid about all this cloud stuff, but I'm only looking for the best solution/improvement.

**Comment by ddurdle** [comment]
Great suggestion.  encfs I've been using for > 6 years.  It is out-dated, and a new version has been talked about for years.

encfs was never really designed for "cloud" -- it was designed when there was no cloud.

I'll look into cryptomator and if it is doable, I'll implement support for it.

**Comment by joemarshalljm** [comment]
Has there been much movement in add this feature? Good encryption is key for me. 

This plugin looks great btw, I'm gonna have a play this weekend

**Comment by ddurdle** [comment]
I installed Cryptomator and I'm playing around with how it works to determine if it is workable into the plugin.  From what I dug into, see no issues yet.

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
