### ISSUE TITLE
Testing 0.2.2 - Picture add-on - Folders are empty

### ISSUE THREAD

**Issue by gbraux** [ddurdle/Amazon-Cloud-Drive-for-KODI#15]
Hi, and thx for the great job on this Kodi Addon !

I just downloaded and installed the test build 0.2.2 (wanted to test the picture add-on and especialy the slideshow capabilites - that was not working with the 0.1.x builds).

I enrolled successfuly, & I can see all my top-level folders ... But they are all empty !
FYI, I can get the folders content on the stable 0.1.x builds ...

Thx,
Guillaume.

**Comment by ddurdle** [comment]
investigating

**Comment by ddurdle** [comment]
my attempt to enable shared folders for testing in 0.2.2 broke all non-shared folders.  Fixed now and I just did a slideshow preview in 0.2.3 to confirm

**Comment by ddurdle** [comment]
promoted to stable
