### ISSUE TITLE
Thumbnail preview for pictures

### ISSUE THREAD

**Issue by gbraux** [ddurdle/Amazon-Cloud-Drive-for-KODI#16]
Hi !

It would be nice to have preview/thumbnails of pictures when browsing in icon mode ... Currently, the only way to browse is through the filenames, which can be quite a challenge when you are looking for a specific picture :-)

It looks like the Amazon Drive API is exposing a method to get a thumbnail : https://forums.developer.amazon.com/questions/22532/any-way-to-get-thumbnails-for-images.html

Br,
Guillaume.

**Comment by ddurdle** [comment]
Issue is that for some reason Amazon is returning a stat error when KODI tries fetch the stats on the thumbnails.  This is when using either the thumbnail link or content_url + viewbox.

**Comment by ddurdle** [comment]
GetImageHash - unable to stat url 

Happens randomly.  In 1 directory with 3 files, 2 out of 3 fail, on another directory of 5 files, all 5 fail.

**Comment by ddurdle** [comment]
if you open the URL in a browser, works fine.  still fails in KODI.  Not related to auth.

**Comment by ddurdle** [comment]
Found a defect in KODI - https://github.com/xbmc/xbmc/pull/6562

**Comment by gbraux** [comment]
This defect has been fixed in Kodi Jarvis 16.1 ...
I have this realease, so if you can push your work to the testing branch, I can have a look.

Guillaume.

**Comment by ddurdle** [comment]
There is nothing to push.  The reason the icons are not loading for you is that the calls to Amazon are failing.  It retrieves only the first and fails all subsequent calls.  The reason for this is tied to this bug referenced at https://github.com/xbmc/xbmc/pull/6562.  They talk about backporting the fix.

The only alternative would be to have the plugin manually download the icons.

**Comment by ddurdle** [comment]
The obvious way to work around the issue is to have the plugin download and store the thumnails somewhere, and feed them to KODI.  I thought of a better way that doesn't involve doing this. 

Will you have cycles this week to test?

**Comment by gbraux** [comment]
The Kodi fix you are referencing has been backported, and is part of Kodi Helix+ ...
So it may not be the main reason od the issue ...

**Comment by ddurdle** [comment]
Added a streamer class for handling thumbnail queries against Amazon Cloud Drive to bypass the KODI bug.  It's fetching and displaying the icons.  In testing stage in 0.2.6

**Comment by gbraux** [comment]
Hi Durdle,

Thx for the work on this ;-)
Unfortunately, I just tested the 0.2.6 testing branch, and I am not seeing any thubnails ...

FYI, I fully uninstalled / reinstalled the extension to ensure that it was not an upgrade issue. Note that my amazon account informations are still availlable after reinstall, but you may store permanently somewhere ...

Guillaume.

**Comment by gbraux** [comment]
FYI, my logs : 
[kodi.txt](https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/files/560415/kodi.txt)

You can see the streamer crashing ...

**Comment by ddurdle** [comment]
What kind of device is this KODI installed on (OS?)?

**Comment by ddurdle** [comment]
Oh it's OSMC.  It's all I use :)

What is strange is there is a NOTICE statement that should post the URL in the log (line 58) which I don't see anywhere actually showing up in the log, yet the error is on line 62.

**Comment by ddurdle** [comment]
with testing, clicking re-generate thumbnails (from right-click context menu):

11:21:47 T:139992527247104   DEBUG: Caching image 'http://localhost:8011/templink/yD5jCHPh6QI8qdbqy_8C0CZTUjRenKfdOqK4t5-Gp-wN8EcoE?viewBox=200' to '7/75887a47.jpg':
11:21:47 T:139992527247104   DEBUG: cached image 'special://masterprofile/Thumbnails/7/75887a47.jpg' size 200x46
11:21:47 T:139993336674048  NOTICE: https://content-na.drive.amazonaws.com/cdproxy//

**Comment by gbraux** [comment]
Unfortunately, the issue is still there, even wit the lastest testing build (and better, I had to restore a kodi image on my RPi, as my SD card got corrupted, so you extension was never installed in the backup image ...).

I also clicked on re-generate thumbnails as asked, but nothing special in the logs.
I enabled log tracing in the extension, but I strangely do not see any debug messages in the logs ... But there may be something to do on Kodi level ...

New logs : 
[kodi2.txt](https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/files/560642/kodi2.txt)

**Comment by ddurdle** [comment]
A trick for the SD card corruption is to use read-only.  Works well on OSMC.  SD cards are notoriously bad, some brands worse then others, so less you write to them, the better.  Especially with slight voltage drops during writing.  Even when using good power adapters, if the cable is long, it can wreck havoc on reliability.  In read-only mode, even if voltage drops, no corruption :)  On all my TV KODI OSMC units, I use read-only and I've never ran into corruption.  On my KODI units that I use on lapdocks (for demonstrations, etc), I never got around to putting them in read-only, and they go corrupt around 1-2 times a year.

**Comment by ddurdle** [comment]
Are you accessing the plugin through Pictures, Picture Add-ons, then selecting Amazon Cloud Drive, etc?

**Comment by ddurdle** [comment]
The reason I ask is, normally in the log it displays warnings that it cannot determine the picture type of a directory, if you are navigating within the plugin, directories are showing and KODI tries to determine if a directory itself is a picture.  I don't see any of this in your logs.  Nothing of Amazon or plugin nature in the second log at all.  Makes me wonder how you are trying to view the photos on the device.

**Comment by gbraux** [comment]
Yes, I am accessing the extension through Image > Amazon Plugin > My folders.
I also tried to open the extension directly, but it just opens it in video mode (8:00 PM in the logs ...).

FYI, I can see the Kodi process listening on port 8011
tcp        0      0 0.0.0.0:8011            0.0.0.0:*               LISTEN      974/kodi.bin

[kodi3.txt](https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/files/560676/kodi3.txt)

**Comment by gbraux** [comment]
And if a try a wget on any on the thumbnail that are generating an error in the log :

wget http://localhost:8011/templink/ZuqUz9qqX8hTpMDhHuz2BBhy1rl7xNL5tKMJEVTiFSsN8EcoE?viewBox=200

I can get the image file ...
(FYI, if I try to acces this link through a web brower, I get a raw ASCII response - buy you may not send the MIME type in the answer ...).

**Comment by ddurdle** [comment]
So it looks like the streamer is working, if it returns the image this way.  Should work in chrome as well.  I'll update to include the headers.  It works on my KODI development installs without returning a header.

There is a second way of fetching data without using the templink.  The viewBox works on that other method, as well (for retrieving thumbnails).

And if that fails, there is yet another way to retrieve the thumbnails (using the thumbnaillink).

All would need to use the streamer, to get around the get bug.

Finally, KODI normally actually makes a HEAD request before making the image request.  I don't bother to implement this.  In my KODI development environment, it does a HEAD request and then does the GET request, and it works.  Maybe it is getting hung up on the HEAD.  In my case, in my environment, it actually was very clear because it was displaying HEAD not implemented throughout the KODI log -- so I implemented it and returned just an empty response, which did the trick for me.

BTW, you can kill the streamer by passing it /kill, like wget http://localhost:8011/kill.

**Comment by ddurdle** [comment]
I went back and fully implemented HEAD.  I also went back and returned the content-type and content-length in the GET (I don't want to simply forward all the header responses back, because I'm trying to avoid the original issue with one of the header entries provoking an inability to fetch the images).

Seems to respond better.  Going off to test on OSMC.

All in 0.2.7 pushed out.  You don't need to remove the add-on to update.  Just auto-update or update to 0.2.7.  If your device hasn't been rebooted since 0.2.6 was installed, you should run a wget http://localhost:8011/kill prior to testing in 0.2.7 to ensure the revised streamer class will replace the prior instantiation.

**Comment by ddurdle** [comment]
Don't bother testing 0.2.7.  Generic photo icons when I tested in OSMC.  Will debug it further tomorrow.

**Comment by ddurdle** [comment]
User issue with the repository and in actuality it wasn't updating to 0.2.7 on my OSMC device.  You'll be relieved to know the same http error was being encountered on my OSMC with 0.2.6.

Got the update to show up and updated to 0.2.7.  Working on OSMC.

Please update and test.

**Comment by gbraux** [comment]
So it works with 0.2.8, great job !! ... but it is sooo sloooowww to get the thumbnails ;-)

I am getting about 1 thumbnail / 5 seconds (with a very low quality - but this looks normal) in Kodi icon view. Not really usable at the current stage, knowing that thumbnails are usefull when browsing large images folders ...

The loading order also looks quite strange (ie. you may randomly see some pictures getting dropped).

Another thing I noticed is that when you are browsing the pictures in icon view, the (already loaded - after waiting a few minutes) thumbnails can take several seconds to appear when browsing up/down so you just see empty icons which is quite disturbing ...

FYI, I have no internet bandwidth issue, and the RPi is not showing any CPU overload when the thumbnails are getting loaded. 

I have also no speed issue when browsing my photos thumbnails directly from the Amazon Photo Website. It loads hundreds of thumbnails quite instantly (FYI, thumbnail on the Amazon website are loaded using the following URL type : https://content-eu.drive.amazonaws.com/cdproxy/templink/3Pwjv081JuagH62bvsOrBoPnYrzGXgjYRwN5Vijy0FgpX92IB/alt/thumb?viewBox=277&fit=clip)

My lastest logs (strangely, with thumbnails 200 OK flagged as ERRORS ...):
[kodi - Copy.txt](https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/files/563825/kodi.-.Copy.txt)

**Comment by gbraux** [comment]
There may be something to do around threading to enhanced the loading performance ... In the log, it looks like thumbnails are loaded one after each other, with sometime 5+ seconds between each load ...

**Comment by gbraux** [comment]
(and you may see some thumbnais loading fast in the log - ie. several thumbnais loaded for in the same second - but I have never seen so fast loading on my TV screen !).

When making a tail -f kodi.log, and browsing pictures in icon mode, I can only see 1 or 2 thubnail on TV ... while the logs shows that it has tried to load dozen on them).

Also, it looks like kodi tries to load several times the same thumbnails ... Based on the logs, it looks like 50% of the loads are just duplicates !

**Comment by gbraux** [comment]
Note : I have also tried to set an image cache folder in the Extension config, or change thumbnails quality, but it has no impact on loading time.

**Comment by ddurdle** [comment]
KODI handles the loading of the thumbnails (qty and order).  I provide it a list.  If there is 100 files in the directory, I provide it 100 thumbnail and picture URLs and it goes off and requests them.

The duplicates are actually a HEAD and GET request.  It first requests the headers and then requests the actual thumbnail.  If I don't respond to the HEAD, for some reason OSMC, it won't bother fetching the thumbnail, but it works on other devices.

I noticed if I go out of the directory and go back in, the loaded ones show up.  For some reason KODI isn't refreshing them them.

I'll keep playing around with it.

**Comment by ddurdle** [comment]
I see KODI is still trying to gather the stats on the pictures, and that may or may not be hampering things.  GetImageHash - unable to stat url

**Comment by ddurdle** [comment]
I compared to the Google Drive plugin, loading a directory containing lots of photos.  The thumbnails loaded fast.  If I scroll down a page of icons (10 icons at a time), it would load the 10 icons in 2 seconds, tops.

At least we have a baseline on what it should behave.

**Comment by gbraux** [comment]
Have a quick  look at the logs I sent earlier, as it looks like  It is trying to load the same thumbnails dozens of times, which kind of overload the process, and may explain the huge loading time I am seeing  ...

**Comment by ddurdle** [comment]
debug info:

12:50:35 T:140637573998336  NOTICE: HEAD https://content-na.drive.amazonaws.com/cdproxy//nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80
12:50:35 T:140637573998336  NOTICE: GET https://content-na.drive.amazonaws.com/cdproxy//nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80
12:50:36 T:140637573998336  NOTICE: HEAD https://content-na.drive.amazonaws.com/cdproxy//nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80
12:50:36 T:140637573998336  NOTICE: GET https://content-na.drive.amazonaws.com/cdproxy//nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80
12:50:36 T:140637076707072   DEBUG: CCurlFile::GetMimeType - http://localhost:8011/nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80 -> image/jpeg
12:50:36 T:140637076707072   DEBUG: CFileCache::Open - opening <nodes/1jUJOvWBQOWsDLFR8AxvzA/content> using cache
12:50:36 T:140637076707072   DEBUG: CurlFile::Open(0x7fe89811a8d0) http://localhost:8011/nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80
12:50:36 T:140638584313920   DEBUG: Keyboard: scancode: 0x6f, sym: 0x0111, unicode: 0x0000, modifier: 0x0
12:50:36 T:140638584313920   DEBUG: OnKey: up (0xf080) pressed, action is Up
12:50:36 T:140637573998336  NOTICE: GET https://content-na.drive.amazonaws.com/cdproxy//nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80
12:50:37 T:140637058082560  NOTICE: Thread FileCache start, auto delete: false
12:50:37 T:140637058082560    INFO: CFileCache::Process - Hit eof.
12:50:37 T:140637058082560   DEBUG: Thread FileCache 140637058082560 terminating
12:50:37 T:140637076707072   DEBUG: Caching image 'http://localhost:8011/nodes/1jUJOvWBQOWsDLFR8AxvzA/content?viewBox=80' to 'e/e6589d54.jpg':
12:50:37 T:140637076707072   DEBUG: cached image 'special://masterprofile/Thumbnails/e/e6589d54.jpg' size 80x53

**Comment by gbraux** [comment]
Hi !

I just tested the 0.2.10 build : 
- Python crashes when starting the extension + on -screen Kodi crash alert (see the logs). But the extension is still loading.
- Thumbnails loading a bit more regular, but still heavily slow (about 1/second, and top>bottom loading - if you have 500 pictures in a folder, and want to find a specific picture that is at the end of the folder ... you have to wait 500*1 = 10 minutes).

Logs : 
[kodi - Copy2.txt](https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/files/573116/kodi.-.Copy2.txt)

**Comment by gbraux** [comment]
(I am not seeing any logs about individual thumbnails/streamer loading in the log file anymore ... 
Were you able to solve the issue where the same thumbnail was tried to be loaded dozens of times for unknown reasons that I found here  https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/issues/16#issuecomment-257539617 ?)

**Comment by ddurdle** [comment]
Probably know why the one error is occurring, when it continues.

I somehow got KODI to reduce the number of attempts to read a thumbnail from 5 times to 3.

Realized that the Amazon Cloud Drive service doesn't respond to HEAD requests, so this is why thumbnails never loaded previously.  And KODI insists on making them.

Oddly enough, if you load a directory containing thumbnails in video addons, it only makes a single GET request.  Even works without these tweaks because it doesn't make HEAD requests.  You can't view pictures in video addons.  But it is interesting that the fetching behaviour is different.

I'm experimenting with a few other things.

**Comment by ddurdle** [comment]
promoted to stable
