### ISSUE TITLE
strm files Generated are not well managed by scrapers

### ISSUE THREAD

**Issue by TCarnal** [ddurdle/Amazon-Cloud-Drive-for-KODI#17]
After generating the strm files from the Amazon cloud plugin, the films scrappers have difficulties parsing the names of the files.
I think the issue comes from the double extension created when you add the .strm at the end of the file.
the solution could be to remove the real extention of the file (.mkv for exemple)

**Comment by ddurdle** [comment]
Which film scraper is having issues?

**Comment by TCarnal** [comment]
the movie default one

**Comment by ddurdle** [comment]
Which version of KODI?  I don't have any issues as it stands with file.strm

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
