### ISSUE TITLE
Amazon Cloud Drive on a 2nd Kodi device

### ISSUE THREAD

**Issue by zanophol** [ddurdle/Amazon-Cloud-Drive-for-KODI#20]
I successfully enabled ACD via the plugin in Kodi 16.1 for my first device. However, in going through the setup for the second device on Kodi 16.1, I am unable to successfully configure it due to an apparent failure to accept the code I generated which was different from the first, and later, the same code with no difference in outcome. I did notice the first time I was successful, the message "Your Amazon OAUTH2 Code is VALUEHERE" was generated, but after the second and all subsequent attempts, I receive "Your Amazon OAUTH2 Code is undefined." Is this the problem?

The actual error on the Kodi ACD addon complains about failure to access the code.

Is having two instances of Kodi accessing the same ACD instance supported? I should think so. I have even tried copying the addon files from the working instance to the non-working instance with no success.

**Comment by ddurdle** [comment]
I'm registered on about 6 devices.

First off, yes, don't resuse the same code on multiple devices.  You must use a unique one on each account.  Are you having the KODI fetch the code within 60 seconds of the code being issued?  They seem to have a short life.

Copying the settings.xml file from one instance to another will avoid needing to register it.

What device is this second KODI?  It sounds like maybe the problems are deeper, like it cannot to HTTPS.

**Comment by zanophol** [comment]
Both devices are Amazon Fire TV's that have been rooted. Do you mean the settings.xml from plugin.video.acd/resources?

**Comment by ddurdle** [comment]
Settings from userdata/addons/ plugin.video.acd/settings.xml.   You can
copy this file between devices and you won't need to enroll the devices
individually.
