### ISSUE TITLE
add own encryption

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/Amazon-Cloud-Drive-for-KODI#28]

**Comment by slappysmurf** [comment]
Great add-on for ACD in Kodi.  

Will this issue (#28) encompass adding support for rclone encrypted files/folders? 

Would it be feasible to add support for rclone?

**Comment by ddurdle** [comment]
rclone is closed source.

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
