### ISSUE TITLE
Load remote subtitle

### ISSUE THREAD

**Issue by vincentkwok** [ddurdle/Amazon-Cloud-Drive-for-KODI#31]
Tried put subtitle with same file name (video.ass && video.mkv) in the same directory but still could not be loaded. 

Also, would suggest to support remote subtitle directory as well

**Comment by geniejhang** [comment]
Same here, tested with srt and smi.

I think I saw there's a piece of code loading srt files automatically, but seems not working.

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
