### ISSUE TITLE
Loss of auth?

### ISSUE THREAD

**Issue by flamingghost** [ddurdle/Amazon-Cloud-Drive-for-KODI#32]
I've seen this in a few apps now with Amazon Cloud.. After 40 minutes - 1 hour, the stream will stop and I'll need to exit and re-enter for the video for it to play again for another 40 minutes - 1 hour. 

Is it possible to implement a new auth key/connection automatically when streaming of the file stops instead of having to exit and select 'continue from..'

Thanks

**Comment by ddurdle** [comment]
investigating

**Comment by ddurdle** [comment]
merge with https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/issues/33
