### ISSUE TITLE
Automatically mark as "watched" after stream completion with library integration

### ISSUE THREAD

**Issue by jonaskindler93** [ddurdle/Amazon-Cloud-Drive-for-KODI#36]
Kodi won't automatically mark .strm's as "watched" after watching them. AFAIK it has to do with Kodi treating .strm's as playlists and not videos.

However, addons themselves can force the action of marking the status as "watched" to get around Kodi's limitations.

Would be awesome if this could get added

**Comment by flamingghost** [comment]
+1 <3

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
