### ISSUE TITLE
[Enhancement]Implement the "play using" command

### ISSUE THREAD

**Issue by vmacavero** [ddurdle/Amazon-Cloud-Drive-for-KODI#39]
Hi, thanks for this incredible plugin.
Is it possibile to implement a menu-command (like kodi has ) to "play to" some dlna device like a tv or generic player ?

Thanks.

**Comment by ddurdle** [comment]
Can you give an example of a plugin that implements this so I can understand how it would function?

**Comment by vmacavero** [comment]
hi ddurdle, thanks for answer.
It's already implemented out of the box in kodi. If you have a video file in library, with right click you have "play to" and then you can select any dlna "renderer" (i think it's the right word) that exposes the service.
I hope i was clear. If you want i'll send a little video.
Thanks, again.
Victor

**Comment by vmacavero** [comment]
hi ddurdle, did you had time to work on the "play using..." option ?

Thanks.

Victor

**Comment by ddurdle** [comment]
I will try to find time to schedule this change.

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
