### ISSUE TITLE
Fix subtitles

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/Amazon-Cloud-Drive-for-KODI#41]
enable subtitles on amazon cloud drive plugin that exists on the same folder as the video

**Comment by PCostaPT** [comment]
Hi, ddurdle any news about this issue?
Its very much needed!
Tks...

**Comment by tuppaacc** [comment]
scan KODI files (metadata) from cloud?

Is there a way for Mediafire, Amazon, Gdrive etc. to display metadata?
Currently it only displays the tittle but no cover art or info.



SORRY TO POST HERE but I don't know how to contact you, your twitter hasn't been updated in ages.

**Comment by ddurdle** [comment]
No method to scan metadata info at this time.

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
