### ISSUE TITLE
Constant errors

### ISSUE THREAD

**Issue by flamingghost** [ddurdle/Amazon-Cloud-Drive-for-KODI#48]
When trying to play any media, browse the drive, create strm files.

Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'URLError' object has no attribute 'code'
AttributeError: 'URLError' object has no attribute 'code'

Can provide logs if you can't reproduce.

The item/folder will eventually load if I repeated keep clicking the link thought it can take 30 clicks before the media starts or folder opens

**Comment by ddurdle** [comment]
Amazon Cloud Drive services API has been acting up since Saturday night.  It seems to be getting a bit better since this morning (random failures vs 100% failures).

Since this is not a bug but an issue with the service, marking invalid.

**Comment by ddurdle** [comment]
Seems like either Amazon hasn't fixed the issue or hasn't realized they have an issue.

Created this issue to handle retrying when the API is struggling.  

https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI/issues/49
