### ISSUE TITLE
EncFS Support

### ISSUE THREAD

**Issue by jwmoss** [ddurdle/Amazon-Cloud-Drive-for-KODI#5]
It would be great if you were to support streaming from EncFS mounted directories or files!

https://vgough.github.io/encfs/

Thanks! Keep it up!

**Comment by ddurdle** [comment]
just to be clear, I do intend on supporting encfs.  I've been testing it in my Google Drive plugin for the past year, to judge best how to move forward with support to other cloud plugins.

**Comment by ddurdle** [comment]
If you want to test support, please let me know

**Comment by cutter** [comment]
I'm happy to test support.

**Comment by ddurdle** [comment]
Many more people have reached out for support for this feature.  It is now on the top of my list.

**Comment by SebJansen** [comment]
Please please ^^

**Comment by JohnnyCalavera** [comment]
You should note though that encfs is absolutely NOT the right choice when it comes to cloud sync. 
The developer stated that he's working on a version 2.0 to address those issues. Maybe we should wait just a bit longer or look for an alternative. 

Source: https://defuse.ca/audits/encfs.htm

**Comment by ddurdle** [comment]
It is adequate for obfuscation, which is what most users desire (to hide their media from Amazon's eyes).  As the creators point out, it should not be used for sensitive material that you need secured.

Since the enablement for encfs is already done, it will be enabled while search for alternatives is done.

**Comment by JohnnyCalavera** [comment]
Alright! I get your point. Thanks for the effort you put into this so far.

**Comment by ddurdle** [comment]
You may drop suggestions here as well.  There are other tools like rclone and odrive that have encryption options, but they are all using their own developed encryption methods (well, following standards in use by other tools) and make their options closed to general use.  I thought about developing my own (and I rolled a class to do so earlier) but I don't want to pretend to be an encryption expert nor want to maintain something.  Also, I don't want to force users to store data using my method of encryption and have it not readable by any other tool.  https://github.com/cryptomator/cryptomator is one user suggestion.

**Comment by JohnnyCalavera** [comment]
I tried rclone in the past and it uses xsalsa20 now - a stream cipher. I'm not sure whether this is notably better for media streaming purposes than a block cipher. 

There are different tools that provide encrypted cloud backups, but I couldn't tell which one should be used. Neither do the guys at emby who are looking for encrypted sync and streaming solutions, too. 

Look at the comparison:
https://emby.media/community/index.php?/topic/39675-cloud-sync-needs-encryption/

**Comment by navigonic** [comment]
Wait, does EncFS work with the plugin now?

**Comment by ddurdle** [comment]
Correct -- https://www.youtube.com/watch?v=uvJ4jpzt7Uo

What is supported at this point:
- music playback
- video playback
- photo playback (except kodi slideshow, but right-click start slideshow works) -- plans to get this working

IV chaining is supported but only in non-prefer to stream mode (and non-single file mode).  Plans to get IV chaining working with all methods

STRM file generation and playback works with encfs.   Subtitles should also work (must be within same Amazon Cloud Drive folder).

Working on plans for other encryption methods.

**Comment by navigonic** [comment]
Strange, I can't get the plugin to auth, the password / passcode slider remains greyed out, using the oAuth presented on the signup page doesn't seem to work

**Comment by ddurdle** [comment]
Use the enroll account when you start the plugin.

**Comment by navigonic** [comment]
Hi again! Where would one enter the encFS password? I don't see any option under Encryption? I'm also assuming one has to mount the ACD using something like ACD_CLI in order to be able to find it using encfs source? Cheers

**Comment by ddurdle** [comment]
promoted to stable

**Comment by sorryusernameisalreadytaken** [comment]
@ddurdle @navigonic Did I need ACD_CLI to run encFS?

**Comment by ddurdle** [comment]
No, you just need to install encfs libraries on the device.  How this is done depends on what kind of device it is.  It could be as simple as "apt-get install encfs" or "homebrew install encfs"

**Comment by sorryusernameisalreadytaken** [comment]
Any suggestion for android 7?

Perhaps one of thoose aps for encFS:
https://play.google.com/store/search?q=encFS&c=apps
or should it work with Termux?

**Comment by ddurdle** [comment]
Sorry, I cannot help you on android.
