### ISSUE TITLE
Video player automaticly stop after 1:03 - 1:04 playing (since kodi 17.6)

### ISSUE THREAD

**Issue by tug912** [ddurdle/Amazon-Cloud-Drive-for-KODI#51]
Hi, thanks for your work but i have issues since install kodi 17.6 !

Stream player stop automaticly after 1:03 - 1:04 playing

Never had this issue before.
I thinks it's something with kodi 17.6 (of course i use the last addon version)

Any idea or update for the addon ?

Thanks

**Comment by ddurdle** [comment]
this plugin is now retired due to amazon shutting down the API
