### ISSUE TITLE
Import Videos to Kodi Library

### ISSUE THREAD

**Issue by NunoFilipeSantos** [ddurdle/Amazon-Cloud-Drive-for-KODI#7]
The ability to import video files (TV Shows & Movies) to Kodi's library would be amazing.

**Comment by ddurdle** [comment]
The feature is already there.  Just need better documentation on it.  It will be further enhanced as well.

To load your content into KODI, on a file or folder, right-click and select Save STRM.  It will create STRM files that can be imported into KODI.  If you select parse TV / parse movies in Advance in plugin settings, it will try to structure your STRM files into a structure that facilitates better importing into KODI.

**Comment by NunoFilipeSantos** [comment]
:+1:  Thank you very much! I will wait for the enhancements then.

**Comment by iz8mbw** [comment]
I will wait for the enhancements too!

**Comment by ddurdle** [comment]
Save STRM should already be in the plugin.

**Comment by ddurdle** [comment]
promoted to stable
