### ISSUE TITLE
Big Mkv Files

### ISSUE THREAD

**Issue by phgeraldes** [ddurdle/Amazon-Cloud-Drive-for-KODI#9]
Hi there, first off all great work with this addon, i´m having trouble playing big files, i have one 12Gb mkv that is not starting playing. Is there any file size limit.
Thanks

**Comment by ddurdle** [comment]
There is no file size limit.  I have bluray rips > 35GB and they playback just fine.

The key is that the media file needs to be streamable.  Many MKV files tend to have the media playback information at the end of the file -- you need to download the entire file before you may start playing it back, hence not streamable.

To ensure a file is streamable, it has to have the playback information at the start of the file.  I'm a bit fuzzy on how to check with ffmpeg/avconv, but you can convert a file using ffmpeg/avconv using -movflags faststart -c copy.  This will push the information to the start of the file and it'll be streamable.  With -c copy, there is no transcoding and the audio and video is not affected.

**Comment by phgeraldes** [comment]
Hi there thanks for the quick reply, i can reproduce the mkv files well on the amazon cloud drive app on android as well on windows with network drive on vlcplayer, thats why i´m asking if there´s any file size limit.
It´s very strange playing well with other apps but on the addon can´t reproduce.

**Comment by ddurdle** [comment]
So the file is under 20 mins long?  The Amazon cloud drive site won't
stream > 20 min videos and I don't think MKVs at all.  The Amazon app on
the phone I thought would have the same restrictions.

It is possible the app is using a transcoded version of the file.

Not sure about Windows net drive.

If the plugin could accept shares I would share you a large video file to
test.  The Amazon share isn't accessible using the Amazon api and I never
got around to working around that.

**Comment by phgeraldes** [comment]
Hi, again here´s the log file:

22:54:21 T:2244 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=NmjLH8TeQAefx6S_MJuTIQ&filename=78aJu8-CRBK0AFPk_WU-6g&title=Pan+-+2015.avi&content_type=video
22:54:21 T:2244   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=NmjLH8TeQAefx6S_MJuTIQ&filename=78aJu8-CRBK0AFPk_WU-6g&title=Pan+-+2015.avi&content_type=video
22:54:21 T:7376 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=NmjLH8TeQAefx6S_MJuTIQ&filename=7g42JRJXT5ep3QoFAH_YHQ&title=Cinderela+2015.avi&content_type=video
22:54:21 T:7376   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=NmjLH8TeQAefx6S_MJuTIQ&filename=7g42JRJXT5ep3QoFAH_YHQ&title=Cinderela+2015.avi&content_type=video
22:54:21 T:7376 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=NmjLH8TeQAefx6S_MJuTIQ&filename=pfjCEUOMSUGMAW7JLFmAVA&title=Titanic-1997.720p.HDTV.x264-YIFY.mp4&content_type=video
22:54:21 T:7376   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=NmjLH8TeQAefx6S_MJuTIQ&filename=pfjCEUOMSUGMAW7JLFmAVA&title=Titanic-1997.720p.HDTV.x264-YIFY.mp4&content_type=video
22:54:25 T:2244 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:25 T:2244   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:31 T:8252  NOTICE: DVDPlayer: Opening: https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo
22:54:31 T:8252 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:54:31 T:6560  NOTICE: Creating InputStream
22:54:31 T:8992   ERROR: XFILE::CDirectory::GetDirectory - Error getting /UnWb6wmzMRe5Wk2_wUU45g/
22:54:32 T:6560   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
22:54:32 T:6560   ERROR: CCurlFile::Open failed with code 400 for https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo
22:54:32 T:6560   ERROR: XFILE::CFileCache::Open - failed to open source <https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo>
22:54:32 T:6560   ERROR: CDVDPlayer::OpenInputStream - error opening [https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo]
22:54:32 T:6560  NOTICE: CDVDPlayer::OnExit()
22:54:32 T:8252   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video]
22:54:32 T:8252  NOTICE: CDVDPlayer::CloseFile()
22:54:32 T:8252  NOTICE: DVDPlayer: waiting for threads to exit
22:54:32 T:8252  NOTICE: DVDPlayer: finished waiting
22:54:32 T:8252  NOTICE: CDVDPlayer::CloseFile()
22:54:32 T:8252  NOTICE: DVDPlayer: waiting for threads to exit
22:54:32 T:8252  NOTICE: DVDPlayer: finished waiting
22:54:33 T:7376 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:33 T:7376   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:36 T:8992 WARNING: Attempt to use invalid handle 6
22:54:45 T:8252  NOTICE: DVDPlayer: Opening: https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo
22:54:45 T:8252 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:54:45 T:616  NOTICE: Creating InputStream
22:54:46 T:1900   ERROR: XFILE::CDirectory::GetDirectory - Error getting /UnWb6wmzMRe5Wk2_wUU45g/
22:54:46 T:616   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
22:54:46 T:616   ERROR: CCurlFile::Open failed with code 400 for https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo
22:54:46 T:616   ERROR: XFILE::CFileCache::Open - failed to open source <https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo>
22:54:46 T:616   ERROR: CDVDPlayer::OpenInputStream - error opening [https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo]
22:54:46 T:616  NOTICE: CDVDPlayer::OnExit()
22:54:46 T:8252   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video]
22:54:46 T:8252  NOTICE: CDVDPlayer::CloseFile()
22:54:46 T:8252  NOTICE: DVDPlayer: waiting for threads to exit
22:54:46 T:8252  NOTICE: DVDPlayer: finished waiting
22:54:46 T:8252  NOTICE: CDVDPlayer::CloseFile()
22:54:46 T:8252  NOTICE: DVDPlayer: waiting for threads to exit
22:54:46 T:8252  NOTICE: DVDPlayer: finished waiting
22:54:47 T:2244 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:47 T:2244   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:51 T:1900 WARNING: Attempt to use invalid handle 7
22:54:52 T:8252  NOTICE: DVDPlayer: Opening: https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo
22:54:52 T:8252 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:54:52 T:9388  NOTICE: Creating InputStream
22:54:52 T:9164   ERROR: XFILE::CDirectory::GetDirectory - Error getting /UnWb6wmzMRe5Wk2_wUU45g/
22:54:53 T:9388   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
22:54:53 T:9388   ERROR: CCurlFile::Open failed with code 400 for https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo
22:54:53 T:9388   ERROR: XFILE::CFileCache::Open - failed to open source <https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo>
22:54:53 T:9388   ERROR: CDVDPlayer::OpenInputStream - error opening [https://content-na.drive.amazonaws.com/cdproxy/nodes/UnWb6wmzMRe5Wk2_wUU45g/content|Authorization=Bearer+Atza%7CIQEBLjAsAhQPepJhysqlaNHxRLEdhclDFCnIeAIUIZoDaQpHhLVFtJJlDpznwGJ1ztlJ5NnM0O7lAv0BZ1VCoZLIcX1I88UzgL2-cpqgghKMfsyNus2xmKwU3yu8ONhe0X0sxKiJlFYLtxTsQQ8Qzg7ZfcEb3wr0FtYehXh6w--dV1ZoEQjRb6swOR5W3lyZemh33GYTxGDVwc-wQP6C4yQzR8dUf-2Ns9sGKxELUF7CW3Sd48ArLnlm4Ivoe1qyP7AjMWS5CpQwmyJpiFZdDXCB4cWrFZmOMoV-dqopcNkH026cY56kzEdQqhL0uwJMXz3HDXQwuKWcZT7dd20qY3blqjami9mrqmUmaPZj3vj8npzeWYzqmreHhLaDVGCh-binzwooXr3isT_jiB3CuxZw5tF8YS7x62lTEWFZhj27bMSINKKCCFYllv2Z-MMggpkFvrOvbSZuWhrgDNZ9VOO3wFnB6xgGxm1r0uVjDBRGzgIB4JpQCzu7KYGKmv5X-nKmlpe8jL3qSAt9zcg16Z8O8RIrbrRhjLwiqavWO6s5_P1rpP2VZvAj9wip-lrRqDXDHvnfAFU8qHJvp1E6OzOSVzVJgoJ1bQc_0LdcIWZ4SDo]
22:54:53 T:9388  NOTICE: CDVDPlayer::OnExit()
22:54:53 T:8252   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video]
22:54:53 T:8252  NOTICE: CDVDPlayer::CloseFile()
22:54:53 T:8252  NOTICE: DVDPlayer: waiting for threads to exit
22:54:53 T:8252  NOTICE: DVDPlayer: finished waiting
22:54:53 T:8252  NOTICE: CDVDPlayer::CloseFile()
22:54:53 T:8252  NOTICE: DVDPlayer: waiting for threads to exit
22:54:53 T:8252  NOTICE: DVDPlayer: finished waiting
22:54:56 T:7376 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video
22:54:56 T:7376   ERROR: InputStream: Error opening, plugin://plugin.video.acd-testing/?mode=video&instance=acd1&folder=6NrFLuvCRAGee-sJrSOwyA&filename=UnWb6wmzMRe5Wk2_wUU45g&title=HarryPotterAndTheChamberOfSecrets2002.mkv&content_type=video

**Comment by ddurdle** [comment]
fixed in 0.1.8
